create table tb_area(
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  nome varchar(30)
);

create table tb_demanda( 
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  nome varchar(30),
  descricao varchar(255),
  id_area integer
);

ALTER TABLE tb_demanda
  ADD CONSTRAINT fk_area_demanda FOREIGN KEY (id_area)
  REFERENCES tb_area (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;
  
create table tb_demanda_lista( 
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  id_demanda integer,
  id_tipo_lista integer,
  nome varchar(30)
);

ALTER TABLE tb_demanda_lista
  ADD CONSTRAINT fk_demanda_lista FOREIGN KEY (id_demanda)
  REFERENCES tb_demanda (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;
  
create table tb_tipo_lista( 
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  descricao varchar(30)
);

ALTER TABLE tb_demanda_lista
  ADD CONSTRAINT fk_tipo_lista FOREIGN KEY (id_tipo_lista)
  REFERENCES tb_tipo_lista (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;
  
create table tb_demanda_lista_atividade( 
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  id_demanda_lista integer,
  id_status_atividade integer,
  nome varchar(100),
  descricao varchar(16777216)
);


ALTER TABLE tb_demanda_lista_atividade
  ADD CONSTRAINT fk_demanda_lista_atividade FOREIGN KEY (id_demanda_lista)
  REFERENCES tb_demanda_lista (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;
  

create table tb_status_atividade( 
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  descricao varchar(30)
);

ALTER TABLE tb_demanda_lista_atividade
  ADD CONSTRAINT fk_status_atividade FOREIGN KEY (id_status_atividade)
  REFERENCES tb_status_atividade (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;
  

create table tb_usuario( 
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  nome varchar(100),
  usuario varchar(100),
  senha varchar(100)  
);

create table tb_demanda_lista_atividade_usuario( 
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  id_demanda_lista_atividade integer,
  id_usuario integer
);


ALTER TABLE tb_demanda_lista_atividade_usuario
  ADD CONSTRAINT fk_demanda_lista_atividade_usuario FOREIGN KEY (id_demanda_lista_atividade)
  REFERENCES tb_demanda_lista_atividade (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;


ALTER TABLE tb_demanda_lista_atividade_usuario
  ADD CONSTRAINT fk_atividade_usuario FOREIGN KEY (id_usuario)
  REFERENCES tb_usuario (id)
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;



alter table TB_AREA add column nivel integer;
alter table TB_AREA add column coluna integer;